# Module: converter
# Overview: Module use to convert csram.mem and input packet generated by RANC to format that can be used by eFabless HWSW co-design project
# Author: Nguyen Phuong Linh (deLini1612) EDABK
# Date: May 2024

def transpose_lines(lines):
    # Transpose lines
    transposed_lines = [''.join([line[i] for line in lines]) for i in range(len(lines[0]))]
    return transposed_lines


def csram_convert(input_file_name, synapse_matrix_file_name, neuron_param_file_name):
    with open(input_file_name, "r") as input_file, \
            open(synapse_matrix_file_name, "w") as synapse_matrix_file, \
            open(neuron_param_file_name, "w") as neuron_param_file:
        # Read all lines from the input file
        lines = input_file.readlines()

        # Extracting the first 256 bits (0 to 255 inclusive) for synapse_matrix.txt
        synapse_matrix_lines = [line[:256].strip() for line in lines]
        # Extracting the remaining bits (256 to end) for neuron_param.txt
        neuron_param_lines = [line[256:-31].strip() for line in lines]

        # Transpose synapse_matrix
        synapse_matrix_transposed = transpose_lines(synapse_matrix_lines)

        # Write transposed synapse_matrix lines to synapse_matrix.txt in reversed order
        for line in reversed(synapse_matrix_transposed):
            synapse_matrix_file.write(line + "\n")

        # Write neuron_param lines to neuron_param.txt
        for line in neuron_param_lines:
            blocks = []
            for i in range(0, 9):
                block = line[i*9+1:i*9+9]
                blocks.append(block)
            rearranged_blocks = [blocks[0], blocks[7], blocks[8], blocks[6], blocks[2], blocks[3], blocks[4], blocks[5], blocks[1], blocks[1]]
            line = ''.join(rearranged_blocks)
            # Add 16 "0" characters to the end of the line for padding
            line += "0"*16
            neuron_param_file.write(line + "\n")

    print("CSRAM conversion complete. Results saved in", synapse_matrix_file_name, "and", neuron_param_file_name)

def extract_8_bits(line):
    # Extracting the 8 bits from the 19th to 26th position (inclusive)
    return line[18:26]

def convert_to_hex(eight_bits):
    # Convert the 8 bits to an integer and then to hexadecimal
    decimal_value = int(eight_bits, 2)
    hex_value = hex(decimal_value)
    return hex_value[2:]  # Removing the '0x' prefix


def packet_convert(input_file_name, output_file_name, wishbone = False):
    with open(input_file_name, "r") as input_file:
        with open(output_file_name, "w") as output_file:
            current_core_num = 0
            last_core_index = None
            for line in input_file:
                # Extracting 8 bits from each line
                eight_bits = extract_8_bits(line.strip())
                # Converting the 8 bits to suitable format
                if (wishbone):
                    hex_value = convert_to_hex(eight_bits)
                    # Multiplying by 4 and adding '0x3000000' to the hexadecimal value
                    final_hex_value = hex((int(hex_value, 16) * 4) + 0x30000000)
                    write_value = final_hex_value[2:]
                else:
                    write_value = '0'*4 + eight_bits

                current_core_index = line.strip()[0:18]
                if (last_core_index is None):
                    last_core_index = current_core_index
                else:
                    if last_core_index != current_core_index:
                        current_core_num = current_core_num + 1
                        if int(current_core_num) > 3:
                            current_core_num = 0
                        last_core_index = current_core_index
                        
                # Writing the final hexadecimal value to the output file
                output_file.write(str(current_core_num) + write_value + "\n")

    print(f"Packet conversion complete with wishbone mode = {wishbone}. Results saved in {output_file_name}")
    
    
def tc_convert(input_file_name, output_file_name):
  with open(input_file_name, 'r') as file:
      data = [line.strip() for line in file.readlines()]

  padding_lines = (16 - len(data) % 16) % 16
  data.extend(['00'] * padding_lines)

  new_data = []
  for i in range(0, len(data), 16):
      merged_line = ''.join(data[i:i+16])
      merged_line = merged_line.ljust(32, '0')
      new_data.append(merged_line)

  with open(output_file_name, 'w') as output_file:
      for line in new_data:
          output_file.write(line + '\n')

  print(f"TC conversion complete, result is saved in {output_file_name}")
